export type SpecRow = { label: string; value: string };
export type Product = {
  id: string;
  title: string;
  brand: string;
  category: string;
  price: string;
  image: string;
  affiliateUrl: string;
  description: string;
  color: string;
  fit: string;
  style: string;
  neck: string;
  sleeve: string;
  pattern: string;
  material: string;
  care: string;
  closure: string;
  country: string;
  asin: string;
  model: string;
  rank: string;
  pockets: string;
  season: string;
  occasion: string;
  specs: SpecRow[];
  sourceText?: string;
};

export const initialProducts: Product[] = [
  // ==========================================
  // TOPS
  // ==========================================
  {
    id: 'jack-jones-12290084-mid-blue',
    title: 'Classic Mid Blue Regular Fit Shirt',
    brand: 'JACK & JONES',
    category: "Men's Shirts",
    price: 'See latest price on Amazon',
    image: '/products/jack-jones-mid-blue.png',
    affiliateUrl: 'https://link.amazon/B0cWbrp7g',
    description:
      'A clean, versatile mid-blue shirt with a classic collared silhouette, long sleeves and a regular fit. A simple everyday layer that works with denim, trousers or smart-casual looks.',
    color: 'Mid Blue',
    fit: 'Regular Fit',
    style: 'Classic',
    neck: 'Collared Neck',
    sleeve: 'Long Sleeve',
    pattern: 'Solid',
    material: '95% Cotton, 5% Cotton - recycled',
    care: 'Machine Wash',
    closure: 'Button',
    country: 'Bangladesh',
    asin: 'B0GX61Z4R9',
    model: '12290084',
    rank: '#14,553 Clothing & Accessories • #642 Men’s Shirts',
    pockets: '1',
    season: '',
    occasion: 'Casual / Smart Casual',
    specs: [
      ['Colour', 'Mid Blue'],
      ['Fitting type', 'Regular Fit'],
      ['Style Name', 'Classic'],
      ['Neck Style', 'Collared Neck'],
      ['Sleeve Type', 'Long Sleeve'],
      ['Shirt Form Type', 'Tuxedo Shirt'],
      ['Collar Style', 'Spread Collar'],
      ['Pattern', 'Solid'],
      ['Apparel Closure Type', 'Button'],
      ['Hemline Form', 'Curved'],
      ['Brand Name', 'JACK & JONES'],
      ['Model Name', '12290084'],
      ['Style Number', '12290084-Mid Blue'],
      ['Country Of Origin', 'Bangladesh'],
      ['Item Type Name', 'Shirt'],
      ['Item Weight', '300 g'],
      ['Material type', 'Cotton Blend'],
      ['Fabric Type', '95% Cotton, 5% Cotton - recycled'],
      ['Product Care Instructions', 'Machine Wash'],
      ['Fabric Stretchability', 'Non-stretchable'],
      ['ASIN', 'B0GX61Z4R9'],
    ].map(([label, value]) => ({ label, value })),
  },
  {
    id: 'peter-england-pcsflslbj05093-black',
    title: 'Peter England Cotton Linen Solid Shirt — Black',
    brand: 'Peter England',
    category: "Men's Shirts",
    price: 'See latest price on Amazon',
    image: '/products/peter-england-black.png',
    affiliateUrl: 'https://link.amazon/B0cpTcD9D',
    description:
      'A lightweight black solid shirt from Peter England with a slim, modern silhouette, collared neckline and long sleeves. Its cotton-linen fabric is designed for easy casual summer styling.',
    color: 'Black',
    fit: 'Slim Fit',
    style: 'Modern',
    neck: 'Collared Neck',
    sleeve: 'Long Sleeve',
    pattern: 'Solid',
    material: '62% Cotton and 38% Linen',
    care: 'Machine Wash',
    closure: 'Button',
    country: 'India',
    asin: 'B0F5QJDPWK',
    model: 'PCSFLSLBJ05093',
    rank: '#2,420 Clothing & Accessories • #138 Men’s Shirts',
    pockets: '1',
    season: 'Summer',
    occasion: 'Casual',
    specs: [
      ['Colour', 'Black'],
      ['Fitting type', 'Slim Fit'],
      ['Style Name', 'Modern'],
      ['Neck Style', 'Collared Neck'],
      ['Sleeve Type', 'Long Sleeve'],
      ['Shirt Form Type', 'Tuxedo Shirt'],
      ['Collar Style', 'Spread Collar'],
      ['Pattern', 'Solid'],
      ['Season', 'Summer'],
      ['Apparel Closure Type', 'Button'],
      ['Cuff Style', 'Plain Hem'],
      ['Apparel Occasion and Lifestyle', 'Casual'],
      ['Brand Name', 'Peter England'],
      ['Model Name', 'Cotton Linen Solids F/S Regular Collar-New'],
      ['Style Number', 'PCSFLSLBJ05093'],
      ['Country Of Origin', 'India'],
      ['Item Type Name', 'Shirt'],
      ['Item Weight', '400 g'],
      ['Number Of Pockets', '1'],
      ['Pocket Description', 'Chest Pocket'],
      ['Material type', 'Cotton Blend'],
      ['Fabric Type', '62% Cotton and 38% Linen'],
      ['Product Care Instructions', 'Machine Wash'],
      ['Apparel Fabric Weight Class', 'Lightweight'],
      ['ASIN', 'B0F5QJDPWK'],
      ['Customer Reviews', '4.1 out of 5 stars (112)'],
    ].map(([label, value]) => ({ label, value })),
  },
  {
    id: 'highlander-hlsh008837-white',
    title: 'HIGHLANDER HLSH008837 Solid Mandarin Collar Shirt — White',
    brand: 'HIGHLANDER',
    category: "Men's Shirts",
    price: 'See latest price on Amazon',
    image: '/products/highlander-white.png',
    affiliateUrl: 'https://link.amazon/B0ghQAHR9',
    description:
      'A clean white solid shirt from HIGHLANDER featuring a regular fit and a distinctive mandarin collar. The lightweight 100% cotton fabric makes it an easy summer-ready choice.',
    color: 'White',
    fit: 'Regular Fit',
    style: 'HLSH013828',
    neck: 'Mandarin Neck',
    sleeve: 'Short Sleeve',
    pattern: 'Solid',
    material: '100% Cotton',
    care: 'Machine Wash',
    closure: '',
    country: 'India',
    asin: 'B01N44MVFT',
    model: 'HLSH008837',
    rank: '#13,306 Clothing & Accessories • #585 Men’s Shirts',
    pockets: '',
    season: 'Summer',
    occasion: 'Casual',
    specs: [
      ['Colour', 'WHITE'],
      ['Fitting type', 'Regular Fit'],
      ['Style Name', 'HLSH013828'],
      ['Neck Style', 'Mandarin Neck'],
      ['Sleeve Type', 'Short Sleeve'],
      ['Collar Style', 'Mandarin Collar'],
      ['Pattern', 'Solid'],
      ['Season', 'Summer'],
      ['Cuff Style', 'Plain Hem'],
      ['Brand Name', 'Highlander'],
      ['Model Name', 'HLSH008837'],
      ['Style Number', 'HLSH008837'],
      ['Country Of Origin', 'India'],
      ['Item Type Name', 'Shirt'],
      ['Item Weight', '300 g'],
      ['Manufacturer Part Number', 'HLSH013828'],
      ['ASIN', 'B01N44MVFT'],
      ['Customer Reviews', '3.1 out of 5 stars (16)'],
      ['Fitting type', 'Regular Fit'],
      ['Sleeve Length Description', 'Long Sleeve'],
      ['Is Customisable?', 'No'],
      ['Material type', 'Cotton'],
      ['Fabric Type', '100% Cotton'],
      ['Product Care Instructions', 'Machine Wash'],
      ['Apparel Fabric Weight Class', 'Lightweight'],
      ['Item Length Description', 'Standard Length'],
    ].map(([label, value]) => ({ label, value })),
  },

  // ==========================================
  // BOTTOMS
  // ==========================================
  {
    id: 'levis-511-slim-fit-dark-indigo',
    title: "Levi's 511 Slim Fit Stretch Denim Jeans — Dark Indigo",
    brand: "Levi's",
    category: 'Jeans',
    price: 'See latest price on Amazon',
    image: '/products/levis-511-jeans.jpg',
    affiliateUrl: 'https://link.amazon/B0Levis511',
    description:
      "A modern classic, the Levi's 511 Slim Fit Jeans offer a lean look with built-in stretch for all-day comfort. Crafted with premium dark indigo wash denim that pairs seamlessly with any shirt or sneaker.",
    color: 'Dark Indigo Blue',
    fit: 'Slim Fit',
    style: '511 Slim',
    neck: '',
    sleeve: '',
    pattern: 'Solid Denim',
    material: '99% Cotton, 1% Elastane',
    care: 'Machine Wash',
    closure: 'Button & Zip Fly',
    country: 'India',
    asin: 'B08FGF511L',
    model: '511-0408',
    rank: '#1,120 Clothing & Accessories • #42 Men’s Jeans',
    pockets: '5',
    season: 'All Season',
    occasion: 'Casual / Smart Casual',
    specs: [
      ['Colour', 'Dark Indigo Blue'],
      ['Fitting type', 'Slim Fit'],
      ['Style Name', '511 Slim Stretch'],
      ['Rise Style', 'Mid Rise'],
      ['Pattern', 'Clean Rinse Wash'],
      ['Apparel Closure Type', 'Button and Zip Fly'],
      ['Brand Name', "Levi's"],
      ['Model Name', '511 Slim Fit'],
      ['Style Number', '045114408'],
      ['Country Of Origin', 'India'],
      ['Item Type Name', 'Jeans'],
      ['Item Weight', '550 g'],
      ['Number Of Pockets', '5'],
      ['Material type', 'Stretch Denim'],
      ['Fabric Type', '99% Cotton, 1% Elastane'],
      ['Product Care Instructions', 'Machine Wash Inside Out'],
      ['ASIN', 'B08FGF511L'],
      ['Customer Reviews', '4.4 out of 5 stars (1,840)'],
    ].map(([label, value]) => ({ label, value })),
  },
  {
    id: 'flying-machine-tapered-black-jeans',
    title: 'Flying Machine Jackson Slim Tapered Jeans — Washed Black',
    brand: 'Flying Machine',
    category: 'Jeans',
    price: 'See latest price on Amazon',
    image: '/products/black-jeans.jpg',
    affiliateUrl: 'https://link.amazon/B0FMB1kJeans',
    description:
      'Urban washed black tapered jeans engineered with high-recovery stretch denim. Designed with subtle whiskering and a contemporary ankle taper that highlights sneakers and loafers.',
    color: 'Washed Black',
    fit: 'Slim Tapered',
    style: 'Jackson Tapered',
    neck: '',
    sleeve: '',
    pattern: 'Washed Solid',
    material: '98% Cotton, 2% Spandex',
    care: 'Machine Wash',
    closure: 'Zip Fly',
    country: 'India',
    asin: 'B09FMJK821',
    model: 'FMJN0982',
    rank: '#3,540 Clothing & Accessories • #180 Men’s Jeans',
    pockets: '5',
    season: 'All Season',
    occasion: 'Streetwear / Casual',
    specs: [
      ['Colour', 'Washed Black'],
      ['Fitting type', 'Slim Tapered Fit'],
      ['Style Name', 'Jackson'],
      ['Rise Style', 'Mid Rise'],
      ['Pattern', 'Washed'],
      ['Apparel Closure Type', 'Zip Fly with Button'],
      ['Brand Name', 'Flying Machine'],
      ['Model Name', 'Jackson Slim Tapered'],
      ['Item Type Name', 'Jeans'],
      ['Item Weight', '520 g'],
      ['Number Of Pockets', '5'],
      ['Material type', 'Cotton Spandex'],
      ['Fabric Type', '98% Cotton, 2% Spandex'],
      ['Product Care Instructions', 'Machine Wash Warm'],
      ['ASIN', 'B09FMJK821'],
    ].map(([label, value]) => ({ label, value })),
  },

  // ==========================================
  // SHOES
  // ==========================================
  {
    id: 'nike-court-vision-low-white',
    title: 'Nike Court Vision Low Leather Casual Sneakers — White',
    brand: 'Nike',
    category: 'Shoes',
    price: 'See latest price on Amazon',
    image: '/products/nike-white-sneakers.jpg',
    affiliateUrl: 'https://link.amazon/B0NikeCourt',
    description:
      'Inspired by mid-1980s basketball trends, the Nike Court Vision Low blends a crisp faux leather upper with classic rubber cupsole construction for durable everyday comfort and effortless styling.',
    color: 'Crisp White',
    fit: 'Regular Width',
    style: 'Low-Top Sneaker',
    neck: '',
    sleeve: '',
    pattern: 'Colorblocked Solid',
    material: 'Synthetic Leather & Rubber Sole',
    care: 'Wipe with Clean Dry Cloth',
    closure: 'Lace-Up',
    country: 'Vietnam',
    asin: 'B08CVL9201',
    model: 'CD5463-100',
    rank: '#480 Clothing & Accessories • #12 Men’s Fashion Sneakers',
    pockets: '',
    season: 'All Season',
    occasion: 'Casual / Everyday',
    specs: [
      ['Colour', 'White / White'],
      ['Shoe Width', 'Medium'],
      ['Style Name', 'Court Vision Low'],
      ['Toe Style', 'Round Toe with Perforations'],
      ['Apparel Closure Type', 'Lace-Up'],
      ['Brand Name', 'Nike'],
      ['Model Name', 'Court Vision Low CD5463'],
      ['Country Of Origin', 'Vietnam'],
      ['Item Type Name', 'Sneakers'],
      ['Sole Material', 'Rubber Cupsole'],
      ['Outer Material', 'Synthetic Leather'],
      ['Product Care Instructions', 'Wipe with dry cloth'],
      ['ASIN', 'B08CVL9201'],
      ['Customer Reviews', '4.5 out of 5 stars (3,290)'],
    ].map(([label, value]) => ({ label, value })),
  },
  {
    id: 'red-tape-tan-leather-loafers',
    title: 'Red Tape Handcrafted Genuine Leather Moccasin Loafers — Tan',
    brand: 'Red Tape',
    category: 'Shoes',
    price: 'See latest price on Amazon',
    image: '/products/tan-loafers.jpg',
    affiliateUrl: 'https://link.amazon/B0RedTapeTan',
    description:
      'Sophisticated hand-burnished tan leather loafers featuring memory-foam cushioned footbeds and anti-skid TPR soles. Designed for smart-casual events, office styling and evening outings.',
    color: 'Tan Brown',
    fit: 'Slip-On Comfort',
    style: 'Penny Loafer',
    neck: '',
    sleeve: '',
    pattern: 'Solid Burnished',
    material: '100% Genuine Leather',
    care: 'Use Leather Cleaner & Conditioner',
    closure: 'Slip-On',
    country: 'India',
    asin: 'B07RTL8922',
    model: 'RTE3901-TAN',
    rank: '#1,840 Clothing & Accessories • #55 Men’s Loafers',
    pockets: '',
    season: 'All Season',
    occasion: 'Smart Casual / Semi-Formal',
    specs: [
      ['Colour', 'Tan Brown'],
      ['Fitting type', 'Regular Slip-On'],
      ['Style Name', 'Penny Loafer Moccasin'],
      ['Toe Style', 'Almond Apron Toe'],
      ['Brand Name', 'Red Tape'],
      ['Model Name', 'RTE3901 Handcrafted'],
      ['Item Type Name', 'Loafers'],
      ['Sole Material', 'Thermo Plastic Rubber (TPR)'],
      ['Outer Material', '100% Genuine Leather'],
      ['Lining Material', 'Breathable Leatherette'],
      ['ASIN', 'B07RTL8922'],
    ].map(([label, value]) => ({ label, value })),
  },

  // ==========================================
  // ACCESSORIES
  // ==========================================
  {
    id: 'fossil-grant-chronograph-watch',
    title: 'Fossil Grant Chronograph Navy Blue Dial Leather Watch',
    brand: 'Fossil',
    category: 'Accessories',
    price: 'See latest price on Amazon',
    image: '/products/fossil-watch.jpg',
    affiliateUrl: 'https://link.amazon/B0FossilGrant',
    description:
      'Timeless elegance meets vintage aeronautical design. Features an eye-catching navy blue sunray dial with Roman numeral hour markers, three sub-dials and an interchangeable dark brown genuine leather strap.',
    color: 'Navy Blue & Brown',
    fit: '44mm Case / 22mm Strap',
    style: 'Chronograph',
    neck: '',
    sleeve: '',
    pattern: 'Sunray Dial',
    material: 'Stainless Steel Case & Genuine Leather Strap',
    care: 'Water Resistant 50M (5 ATM)',
    closure: 'Single Prong Buckle',
    country: 'Hong Kong',
    asin: 'B00NP69A3U',
    model: 'FS5068',
    rank: '#620 Clothing & Accessories • #18 Men’s Wrist Watches',
    pockets: '',
    season: 'All Season',
    occasion: 'Versatile / Editorial',
    specs: [
      ['Colour', 'Navy Blue Dial / Brown Strap'],
      ['Case Diameter', '44 Millimetres'],
      ['Case Thickness', '12 Millimetres'],
      ['Band Width', '22 Millimetres'],
      ['Movement', 'Quartz Chronograph'],
      ['Water Resistance', '50 Metres (5 ATM)'],
      ['Brand Name', 'Fossil'],
      ['Model Name', 'Grant FS5068'],
      ['Item Type Name', 'Watch'],
      ['Dial Glass Material', 'Mineral Crystal'],
      ['ASIN', 'B00NP69A3U'],
      ['Customer Reviews', '4.6 out of 5 stars (5,400)'],
    ].map(([label, value]) => ({ label, value })),
  },
  {
    id: 'ray-ban-classic-aviator-sunglasses',
    title: 'Ray-Ban Classic Aviator Sunglasses — Gold Frame / Green G-15',
    brand: 'Ray-Ban',
    category: 'Accessories',
    price: 'See latest price on Amazon',
    image: '/products/aviator-sunglasses.jpg',
    affiliateUrl: 'https://link.amazon/B0RayBanAviator',
    description:
      'The iconic Ray-Ban Aviator sunglasses originally designed for U.S. aviators in 1937. Featuring a gleaming gold-tone metal frame, crystal green G-15 UV-protective lenses, and adjustable silicone nose pads.',
    color: 'Gold / Classic Green G-15',
    fit: '58mm Standard Fit',
    style: 'Aviator',
    neck: '',
    sleeve: '',
    pattern: 'Teardrop Silhouette',
    material: 'Metal Frame & Crystal Glass Lens',
    care: 'Clean with Microfiber Cloth',
    closure: '',
    country: 'Italy',
    asin: 'B00080FK54',
    model: 'RB3025-L0205',
    rank: '#310 Clothing & Accessories • #8 Men’s Sunglasses',
    pockets: '',
    season: 'All Season',
    occasion: 'Outdoor / Lifestyle',
    specs: [
      ['Colour', 'Arista Gold / G-15 Green'],
      ['Lens Width', '58 Millimetres'],
      ['Bridge Width', '14 Millimetres'],
      ['Temple Length', '135 Millimetres'],
      ['Frame Material', 'Monel Metal'],
      ['Lens Protection', '100% UV400 Protection'],
      ['Brand Name', 'Ray-Ban'],
      ['Model Name', 'Aviator Classic RB3025'],
      ['Item Type Name', 'Sunglasses'],
      ['Country Of Origin', 'Italy'],
      ['ASIN', 'B00080FK54'],
    ].map(([label, value]) => ({ label, value })),
  },
];
