'use client';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, Sparkles, Search, SlidersHorizontal, Shirt, Footprints, Watch, Wand2 } from 'lucide-react';
import { initialProducts, Product } from '../data';
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';

export default function Home(){
 const [products,setProducts]=useState<Product[]>(initialProducts); const [query,setQuery]=useState(''); const [category,setCategory]=useState('All');
 useEffect(()=>{ if(supabase){supabase.from('products').select('*').eq('published',true).order('created_at',{ascending:false}).then(({data})=>{if(data?.length){const map=new Map<string,Product>(); [...initialProducts,...(data as Product[])].forEach(p=>map.set(p.id,p)); setProducts([...map.values()])}}).catch(()=>{});} else {try{const x=localStorage.getItem('fashionfind-products'); if(x){const map=new Map<string,Product>(); [...initialProducts,...JSON.parse(x)].forEach(p=>map.set(p.id,p)); setProducts([...map.values()])}}catch{}}; if(!sessionStorage.getItem('ff-visit-recorded')){sessionStorage.setItem('ff-visit-recorded','1'); if(!supabase){localStorage.setItem('ff-visits',String(Number(localStorage.getItem('ff-visits')||0)+1));} fetch('/api/track',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'visit'})}).catch(()=>{});} },[]);
 const filtered=useMemo(()=>products.filter(p=>(category==='All'||p.category===category||category==='Men'&&p.category.includes("Men")||category==='Women'&&p.category.includes("Women")||category==='Trending'&&p.specs?.some(s=>/rank|reviews/i.test(s.label))||category==='Deals'&&p.price!=='See latest price on Amazon')&&`${p.title} ${p.brand} ${p.category}`.toLowerCase().includes(query.toLowerCase())),[products,query,category]);
 const categories=['All','Men','Women','Shoes','Accessories','Trending','Deals'];
 return <main><section className="hero"><div className="shell heroGrid"><div><span className="eyebrow">● Curated for your style</span><h1>Find Your Next <em>Favorite Look.</em></h1><p>Discover fashion worth wearing. Explore curated styles, build complete looks and shop with confidence.</p><div className="actions"><a className="btn btnDark" href="#collection">Explore Fashion <ArrowRight size={16}/></a><Link className="btn btnLight" href="/style"><Wand2 size={16}/> Create My Style</Link></div><div className="stats"><div><strong>{products.length}+</strong><span>Curated picks</span></div><div><strong>24/7</strong><span>Style discovery</span></div><div><strong>1-click</strong><span>Amazon shopping</span></div></div></div><div className="heroCard"><Image src={products[0].image} alt={products[0].title} width={659} height={879} priority/><div className="floating"><b>Editor's Pick</b><br/><span>{products[0].color} • {products[0].fit}</span></div></div></div></section>
 <section className="section" id="collection"><div className="shell"><div className="sectionHead"><div><h2>Freshly curated</h2><p>Everyday pieces, organized by category and ready to discover.</p></div><div className="glassPanel searchPanel"><SlidersHorizontal size={15}/><input aria-label="Search products" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search finds..."/></div></div><div className="categoryRow">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`cat ${category===c?'active':''}`}>{c}</button>)}</div><div className="grid" style={{marginTop:20}}>{filtered.map(p=><article className="card" key={p.id}><Link href={`/product/${p.id}`}><div className="imageBox"><span className="badge">CURATED FIND</span><Image src={p.image} alt={p.title} width={659} height={879}/></div><div className="cardBody"><div className="brand">{p.brand} · {p.category}</div><h3>{p.title}</h3><p className="desc">{p.description}</p><div className="meta"><span className="chip">{p.color||'Signature'}</span>{p.fit&&<span className="chip">{p.fit}</span>}{p.material&&<span className="chip">{p.material.split(',')[0]}</span>}</div><div className="cardBottom"><span className="price">{p.price}</span><span className="amazon">View on Amazon →</span></div></div></Link></article>)}</div>{!filtered.length&&<div className="empty">No curated finds match your search yet.</div>}</div></section>
 <section className="section styleBanner"><div className="shell"><div className="glassPanel stylePromo"><div><span className="eyebrow"><Sparkles size={13}/> Fashion Studio</span><h2>Build a look, not just a cart.</h2><p>Choose a top, bottom, shoes and accessories. FashionFind turns your selections into a shoppable outfit.</p></div><Link className="btn btnDark" href="/style">Create My Style <ArrowRight size={16}/></Link></div></div></section>
 <footer className="footer"><div className="shell footerGrid"><div><b>FASHIONFIND<span className="dot">•</span></b><p>Discover fashion worth wearing.</p></div><div className="disclosure">FashionFind participates in the Amazon Associates Program. As an Amazon Associate I earn from qualifying purchases. Product information, prices, stock and availability may change on the retailer's website.</div><Link href="/admin">Admin</Link></div></footer></main>
}
